### ISSUE TITLE
Not able to run tests against selenoid

### ISSUE THREAD

**Issue by lorsatti** [salesforce/codeceptjs-bdd#44]
# Steps to reproduce

1. Generate tests via `npx create-codeceptjs-bdd-tests`  
2. Download Selenoid Configuration Manager from https://github.com/aerokube/cm/releases/tag/1.7.2
3. Start selenoid via `./cm selenoid start --vnc --port 4445`
4. Set 
```
# SELENOID OPTIONS
HUB_BASE_HOST = localhost
HUB_PORT = 4445
``` 
in `codecept.env`
4. Start tests via `yarn acceptance --profile selenoid:chrome:88 --grep @smoke --verbose`
5. Getting output:
```
🚀 🚀 🚀   Codeceptjs-BDD Acceptance Tests   🚀 🚀 🚀 

🌏 [docs] gkushang.github.io [repository] github.com/salesforce/codeceptjs-bdd

🌟  Launching 'selenoid:chrome:88' on Webdriver.

🌥️  Tests are running on : Selenoid {"browser":"chrome","version":"88"}

Webdriver: {"url":"https://github.com","browser":"chrome","smartWait":10000,"waitForTimeout":15000,"restart":true,"acceptInsecureCerts":true,"protocol":"http","host":"localhost","port":4445,"path":"/wd/hub","desiredCapabilities":{"acceptInsecureCerts":true,"selenoid:options":{"browserName":"chrome","version":"88","enableVNC":true,"enableVideo":false,"screenResolution":"1280x1024x24"}}}

🗑️  cleaning report dir "/Users/lorenzoo/git/codeceptjs-bdd-test/tests/acceptance/report" ...

CodeceptJS v3.0.2
Using test root "/Users/lorenzoo/git/codeceptjs-bdd-test"
Helpers: Driver_commands, custom_methods, REST, WebDriver
Plugins: screenshotOnFail, allure, retryFailedStep, tryTo

Login Tests (mocha) --
    [1]  Starting recording promises
  Fred logs in successfully @login_mocha @smoke
    [1] Error | Error: Can't connect to WebDriver.
Error: Failed to create session.
Requested environment is not available

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
  ✖ "before each" hook: codeceptjs.before for "Fred logs in successfully @login_mocha @smoke" in 39ms
    [1] Error | Error: Can't connect to WebDriver.
Error: Failed to create session.
Requested environment is not available

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
Error: Can't connect to WebDriver.
Error: Failed to create session.
Requested environment is not available

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

-- FAILURES:

  1) Login Tests (mocha)
       "before each" hook: codeceptjs.before for "Fred logs in successfully @login_mocha @smoke":
     Can't connect to WebDriver.
Error: Failed to create session.
Requested environment is not available

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
  Error: Failed to create session.
  Requested environment is not available
      at Object.startWebDriverSession (node_modules/webdriver/build/utils.js:34:15)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Function.newSession (node_modules/webdriver/build/index.js:35:45)
      at Object.exports.remote (node_modules/webdriverio/build/index.js:53:22)
      at WebDriver._startBrowser (node_modules/codeceptjs/lib/helper/WebDriver.js:516:24)
```
``

**Comment by lorsatti** [comment]
Sorry, my fault: I was missing `--force` parameter while calling `./cm selenoid start --vnc --port 4445 --force`. With `--force` all necessary docker images are downloaded automatically.
