### ISSUE TITLE
Wrong JSON content

### ISSUE THREAD

**Issue by 11ange** [salesforce/codeceptjs-bdd#85]
Hello! I'm getting this error when running commmand on windows:
npx create-codeceptjs-bdd-tests

===============================
🚀 Installing dependencies...

yarn add v1.22.19
error An unexpected error occurred: "C:\\Salesforce\\test\\codeceptjs-bdd\\package.json: Expected ',' or '}' after property value in JSON at position 779".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Salesforce\\test\\codeceptjs-bdd\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
C:\Users\lolg\AppData\Local\npm-cache\_npx\bd4f35f9a4c924f0\node_modules\create-codeceptjs-bdd-tests\cli\update.package.js:27
        throw new Error('Yarn command failed.');
              ^

Error: Yarn command failed.
    at exports.installDependencies (C:\Users\lolg\AppData\Local\npm-cache\_npx\bd4f35f9a4c924f0\node_modules\create-codeceptjs-bdd-tests\cli\update.package.js:27:15)
    at run (C:\Users\lolg\AppData\Local\npm-cache\_npx\bd4f35f9a4c924f0\node_modules\create-codeceptjs-bdd-tests\cli\create.js:150:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.3.0
=============================
log file yarn-error.log is attached.

[yarn-error.log](https://github.com/salesforce/codeceptjs-bdd/files/11983001/yarn-error.log)

Error seems to be on double quotes on package.json:
![image](https://github.com/salesforce/codeceptjs-bdd/assets/37086813/e3dfd48b-edc8-40ea-8e2d-d62b7a724097)

thank you!

**Comment by gkushang** [comment]
this should have been fixed by "https://github.com/salesforce/codeceptjs-bdd/pull/86", please reopen if it's not
